# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs: 
      version:
        description: "Please provide image version"
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "VER=${{ github.sha }}" >> $GITHUB_ENV
          
      - name : set APP_VERSION1
        if: ${{ github.event.inputs.version != '' }}
        run: |
          VER=${{ github.event.inputs.version }}
          echo "VER=${VER}" >> $GITHUB_ENV

      - run: "echo hello ${{ github.sha }}"
      - run: "echo hello ${VER}"
    

