# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs: 
      version:
        description: "Please provide image version"
        required: false
        default: '1.1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - run: "echo hello ${{ github.sha }}"

